const styles = {
  app: { background: "#0b0e14", color: "#d6dae3", minHeight: "100vh", fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace", fontSize: 12.5, padding: "16px 20px 48px", boxSizing: "border-box", transition: "padding-right .2s ease" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", borderBottom: "1px solid #1c2230", paddingBottom: 12, marginBottom: 10, flexWrap: "wrap", gap: 12 },
  title: { fontSize: 18, fontWeight: 700, letterSpacing: 1.5, color: "#e8ecf3" },
  subtitle: { fontSize: 11, color: "#6b7385", marginTop: 2 },
  controls: { display: "flex", gap: 14, alignItems: "flex-end", flexWrap: "wrap" },
  ctrlLabel: { display: "flex", flexDirection: "column", gap: 4 },
  ctrlText: { fontSize: 10, color: "#6b7385", letterSpacing: 1 },
  mondayBadge: { display: "flex", flexDirection: "column", gap: 4, background: "#11151f", border: "1px solid #244068", borderRadius: 4, padding: "4px 10px" },
  mondayDate: { fontSize: 15, fontWeight: 700, color: "#6fa8e6", fontVariantNumeric: "tabular-nums" },
  input: { background: "#11151f", border: "1px solid #232a3a", color: "#e8ecf3", padding: "6px 8px", borderRadius: 4, fontFamily: "inherit", fontSize: 13, outline: "none" },
  toolbar: { display: "flex", alignItems: "center", gap: 12, marginBottom: 16, flexWrap: "wrap" },
  toolBtn: { background: "#1f2937", border: "1px solid #2a3346", color: "#cfd6e4", padding: "5px 12px", borderRadius: 4, cursor: "pointer", fontFamily: "inherit", fontSize: 12 },
  toolBtnGhost: { marginLeft: "auto", color: "#b06a72", borderColor: "#3a1d22", background: "transparent" },
  toolNote: { fontSize: 10.5, color: "#6b7385" },
  loadBanner: { display: "flex", alignItems: "center", gap: 4, flexWrap: "wrap", background: "#13233a", border: "1px solid #244068", color: "#cfd6e4", borderRadius: 6, padding: "8px 12px", marginBottom: 16, fontSize: 12 },
  listaFill: { display: "inline-flex", alignItems: "center", gap: 4, fontSize: 10.5, color: "#9aa3b5" },
  listaAuto: { color: "#7c8597", fontStyle: "italic" },
  mesaMain: { minWidth: 0, transition: "margin-right .2s ease" },
  chatBox: { position: "fixed", top: 0, right: 0, height: "100vh", width: 360, boxSizing: "border-box", display: "flex", flexDirection: "column", background: "#0f1420", borderLeft: "1px solid #22304a", padding: 14, zIndex: 40, transition: "transform .2s ease" },
  chatResults: { flex: 1, overflowY: "auto", marginTop: 8, display: "flex", flexDirection: "column", gap: 8 },
  spinner: { width: 11, height: 11, borderRadius: "50%", border: "2px solid #2a3346", borderTopColor: "#6ea8fe", display: "inline-block", animation: "deskspin 0.7s linear infinite" },
  chatEmpty: { fontSize: 12, color: "#6b7385", lineHeight: 1.5, border: "1px dashed #22304a", borderRadius: 6, padding: 12, background: "#0b0e14" },
  agYou: { alignSelf: "flex-end", maxWidth: "90%", background: "#1d2740", border: "1px solid #2f4166", color: "#dbe6f7", borderRadius: "8px 8px 2px 8px", padding: "6px 9px", fontSize: 12.5, whiteSpace: "pre-wrap" },
  agBot: { background: "#0f1a12", border: "1px solid #244a2c", color: "#d7ead9", borderRadius: "8px 8px 8px 2px", padding: "7px 10px", fontSize: 12.5, whiteSpace: "pre-wrap", lineHeight: 1.45 },
  agTool: { fontSize: 10.5, color: "#7c8597", fontStyle: "italic", padding: "0 2px" },
  agSys: { fontSize: 12, color: "#8ee0a8", background: "#11201400", padding: "2px 2px" },
  chatInputWrap: { flexShrink: 0, paddingTop: 10, borderTop: "1px solid #1c2230", marginTop: 8 },
  chatHead: { display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 11, letterSpacing: 1, color: "#6fa8e6", fontWeight: 700, marginBottom: 8 },
  chatCollapse: { background: "transparent", border: "1px solid #22304a", color: "#9aa4b2", borderRadius: 4, cursor: "pointer", padding: "1px 8px", fontSize: 13 },
  chatInput: { width: "100%", boxSizing: "border-box", background: "#0b0e14", border: "1px solid #232a3a", color: "#e8ecf3", borderRadius: 4, padding: "8px 9px", fontFamily: "inherit", fontSize: 12.5, outline: "none", resize: "vertical" },
  chatReopen: { position: "fixed", top: "50%", right: 0, transform: "translateY(-50%)", background: "#0f1420", border: "1px solid #22304a", borderRight: "none", color: "#6fa8e6", borderRadius: "8px 0 0 8px", cursor: "pointer", padding: "16px 7px", fontSize: 15, zIndex: 40, writingMode: "vertical-rl", letterSpacing: 1 },
  listaPctInput: { width: 44, background: "#0b0e14", border: "1px solid #232a3a", color: "#e8ecf3", borderRadius: 3, textAlign: "right", fontFamily: "inherit", fontSize: 11, padding: "2px 4px", outline: "none" },
  deltaTag: { color: "#a78bfa", fontSize: 9, marginLeft: 2 },
  listaSpread: { borderLeft: "2px solid #7c3aed", background: "#191526" },
  listaInputSpread: { color: "#c4b5fd" },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 11, letterSpacing: 1.2, color: "#6b7385", marginBottom: 8, fontWeight: 600 },
  parseRow: { display: "flex", gap: 8, alignItems: "stretch" },
  select: { background: "#11151f", border: "1px solid #232a3a", color: "#e8ecf3", borderRadius: 4, padding: "0 8px", fontFamily: "inherit", fontSize: 12.5, outline: "none" },
  parseArea: { flex: 1, background: "#0b0e14", border: "1px solid #232a3a", color: "#cfd6e4", borderRadius: 4, padding: 8, fontFamily: "inherit", fontSize: 12, resize: "vertical", outline: "none", lineHeight: 1.5 },
  parseBtn: { background: "#2563eb", border: "none", color: "#fff", padding: "0 16px", borderRadius: 4, cursor: "pointer", fontFamily: "inherit", fontSize: 12, fontWeight: 600, whiteSpace: "nowrap" },
  busy: { background: "#374151", cursor: "default" },
  okMsg: { fontSize: 11.5, color: "#4ade80", marginTop: 8 },
  okSkus: { color: "#6b7385" },
  errorMsg: { fontSize: 11.5, color: "#f87171", background: "#1a1014", border: "1px solid #3a1d22", borderRadius: 4, padding: "5px 7px", marginTop: 8, wordBreak: "break-word" },
  tableWrap: { overflowX: "auto", border: "1px solid #1c2230", borderRadius: 6, maxHeight: "70vh", overflowY: "auto" },
  table: { borderCollapse: "collapse", width: "100%", minWidth: 880 },
  th: { background: "#11151f", color: "#8b94a7", fontSize: 10.5, fontWeight: 600, textAlign: "right", padding: "8px 8px", borderBottom: "1px solid #1c2230", whiteSpace: "nowrap", position: "sticky", top: 0, zIndex: 1 },
  thSku: { textAlign: "left", position: "sticky", left: 0, zIndex: 2 },
  thMine: { color: "#fbbf24" },
  tr: { borderBottom: "1px solid #151a26" },
  td: { padding: "3px 8px", borderBottom: "1px solid #151a26", whiteSpace: "nowrap" },
  tdSku: { textAlign: "left", color: "#cfd6e4", fontWeight: 600, position: "sticky", left: 0, background: "#0b0e14", zIndex: 1 },
  tdCell: { padding: "2px 4px" },
  tdNum: { textAlign: "right", fontVariantNumeric: "tabular-nums", color: "#cfd6e4" },
  tdMuted: { color: "#7b8499" },
  tdMine: { color: "#fbbf24", fontWeight: 700, background: "#15130a", textAlign: "right" },
  catRow: { background: "#0e1218", color: "#8b94a7", fontSize: 10.5, fontWeight: 700, letterSpacing: 1, padding: "5px 8px", textTransform: "uppercase", position: "sticky", left: 0 },
  cellInner: { display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 2 },
  cellInput: { width: 58, background: "transparent", border: "1px solid transparent", color: "#cfd6e4", textAlign: "right", fontFamily: "inherit", fontSize: 12, padding: "3px 4px", borderRadius: 3, outline: "none", fontVariantNumeric: "tabular-nums" },
  // cell backgrounds by freshness / role
  cellBest: { background: "#0f2a17" },                          // mejor precio (verde)
  cellOut: { background: "#2a2410" },                           // outlier (amarillo)
  cellRecent: { background: "#0b2f30" },                        // recién (turquesa)
  cellUpdated: { background: "#10203a" },                       // actualizado (azul)
  cellExpired: { background: "#2a1117" },                       // expirado (rojo)
  // matching input text colors
  inBest: { color: "#4ade80", fontWeight: 700 },
  inOut: { color: "#fbbf24", fontWeight: 700 },
  inRecent: { color: "#6ee7d6" },
  inUpdated: { color: "#9fb4dc" },
  inExpired: { color: "#a86b72" },
  legChip: { display: "inline-block", width: 11, height: 11, borderRadius: 2, marginRight: 4, verticalAlign: "-1px" },
  trendUp: { color: "#f87171", fontSize: 9 },
  trendDown: { color: "#4ade80", fontSize: 9 },
  medTag: { fontSize: 9, color: "#a87f2a" },
  dash: { color: "#3b4252" },
  legend: { display: "flex", gap: 16, flexWrap: "wrap", fontSize: 10, color: "#6b7385", marginTop: 8, alignItems: "center" },
  legBest: { display: "inline-block", width: 10, height: 10, background: "#0f2a17", border: "1px solid #4ade80", borderRadius: 2, marginRight: 4, verticalAlign: "-1px" },
  legOut: { display: "inline-block", width: 10, height: 10, background: "#2a2410", border: "1px solid #fbbf24", borderRadius: 2, marginRight: 4, verticalAlign: "-1px" },
  scoreboard: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(130px, 1fr))", gap: 10 },
  scoreCard: { background: "#11151f", border: "1px solid #1c2230", borderRadius: 6, padding: 12 },
  scoreLeader: { borderColor: "#16a34a", background: "#0e1a12" },
  scoreName: { fontSize: 12, color: "#cfd6e4", fontWeight: 600 },
  scoreWins: { fontSize: 26, fontWeight: 700, color: "#e8ecf3", lineHeight: 1.1 },
  scoreTrack: { height: 5, background: "#1c2230", borderRadius: 3, overflow: "hidden", marginTop: 6 },
  scoreFill: { height: "100%", borderRadius: 3 },
  skuLabel: { display: "inline-flex", alignItems: "center", gap: 6, cursor: "pointer" },
  chk: { accentColor: "#3b82f6", cursor: "pointer", width: 13, height: 13 },
  quoteBar: { display: "flex", alignItems: "center", gap: 10, marginBottom: 12, flexWrap: "wrap" },
  copyBtn: { marginLeft: "auto", background: "#16a34a", border: "none", color: "#fff", padding: "7px 16px", borderRadius: 4, cursor: "pointer", fontFamily: "inherit", fontSize: 12, fontWeight: 600 },
  quoteEditor: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: 12, marginBottom: 14 },
  quoteGroup: { background: "#11151f", border: "1px solid #1c2230", borderRadius: 6, padding: 10 },
  quoteGroupHead: { fontSize: 11, fontWeight: 700, letterSpacing: 1, color: "#8b94a7", textTransform: "uppercase", borderBottom: "1px solid #1c2230", paddingBottom: 6, marginBottom: 6 },
  quoteLine: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, padding: "2px 0", fontSize: 11.5 },
  quoteSku: { color: "#cfd6e4" },
  quotePriceWrap: { display: "inline-flex", alignItems: "center", gap: 3, color: "#fbbf24", fontWeight: 700 },
  quoteInput: { width: 56, background: "#0b0e14", border: "1px solid #232a3a", color: "#fbbf24", textAlign: "right", fontFamily: "inherit", fontSize: 12, fontWeight: 700, padding: "2px 5px", borderRadius: 3, outline: "none", fontVariantNumeric: "tabular-nums" },
  ovTag: { color: "#6b7385", fontSize: 10 },
  quotePreviewLabel: { fontSize: 10.5, color: "#6b7385", marginBottom: 4 },
  quotePreview: { background: "#0b0e14", border: "1px solid #232a3a", borderRadius: 6, padding: 12, fontFamily: "inherit", fontSize: 12.5, color: "#dfe4ee", lineHeight: 1.6, whiteSpace: "pre-wrap", margin: 0, overflowX: "auto" },
  viewNav: { display: "flex", gap: 8, marginBottom: 16, flexWrap: "wrap" },
  viewTab: { background: "#11151f", border: "1px solid #232a3a", color: "#9aa3b5", padding: "9px 18px", borderRadius: 6, cursor: "pointer", fontFamily: "inherit", fontSize: 13, fontWeight: 600 },
  viewTabOn: { background: "#1e293b", borderColor: "#3b82f6", color: "#e8ecf3" },
  invGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(210px, 1fr))", gap: 14, marginBottom: 6 },
  invCol: { display: "flex", flexDirection: "column", gap: 5 },
  invColHead: { fontSize: 10, fontWeight: 700, letterSpacing: 1, color: "#6b7385" },
  invInput: { background: "#11151f", border: "1px solid #232a3a", color: "#e8ecf3", padding: "6px 8px", borderRadius: 4, fontFamily: "inherit", fontSize: 12, outline: "none" },
  invArea: { background: "#0b0e14", border: "1px solid #232a3a", color: "#cfd6e4", padding: "6px 8px", borderRadius: 4, fontFamily: "inherit", fontSize: 12, outline: "none", resize: "vertical", lineHeight: 1.4 },
  invFields: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6 },
  invField: { display: "flex", flexDirection: "column", gap: 3 },
  invFieldLbl: { fontSize: 9.5, color: "#6b7385" },
  selBox: { background: "#0b0e14", border: "1px solid #1c2230", borderRadius: 4, padding: 8, fontSize: 11.5, color: "#9aa3b5" },
  selLine: { marginBottom: 2 },
  selHint: { fontSize: 10, color: "#525a6b", marginTop: 2 },
  newWrap: { marginTop: 10, background: "#11151f", border: "1px solid #244068", borderRadius: 6, padding: 10 },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(3,6,12,0.72)", display: "flex", alignItems: "flex-start", justifyContent: "center", padding: "8vh 16px", zIndex: 1000 },
  // edición de una factura vieja: la sección de Órdenes flota como modal sobre el Historial
  editOverlay: { position: "fixed", inset: 0, background: "rgba(3,6,12,0.78)", display: "flex", alignItems: "flex-start", justifyContent: "center", padding: "4vh 16px", zIndex: 1000, overflowY: "auto" },
  editCard: { background: "#0d1119", border: "1px solid #3a5a1d", borderRadius: 10, padding: 18, width: "min(1080px, 97vw)", marginBottom: 20, boxShadow: "0 24px 70px rgba(0,0,0,0.6)" },
  modalCard: { background: "#0f1420", border: "1px solid #2a4a75", borderRadius: 8, padding: 16, width: "min(720px, 96vw)", maxHeight: "80vh", overflowY: "auto", boxShadow: "0 20px 60px rgba(0,0,0,0.5)" },
  newHead: { fontSize: 11.5, color: "#6fa8e6", fontWeight: 600, marginBottom: 8 },
  newRow: { display: "flex", alignItems: "center", gap: 6, marginBottom: 6, flexWrap: "wrap" },
  newPrice: { display: "inline-flex", alignItems: "center", gap: 2, color: "#fbbf24", fontWeight: 600 },
  newSup: { fontSize: 10.5, color: "#6b7385", minWidth: 50 },
  newAdd: { background: "#16a34a", border: "none", color: "#fff", padding: "5px 12px", borderRadius: 4, cursor: "pointer", fontFamily: "inherit", fontSize: 12, fontWeight: 600 },
  // móvil
  appMobile: { padding: "12px 12px 40px", fontSize: 13 },
  mLoadRow: { display: "flex", gap: 8, marginBottom: 14 },
  mTable: { borderCollapse: "collapse", width: "100%", fontSize: 11.5, tableLayout: "fixed" },
  mTh: { background: "#11151f", color: "#8b94a7", fontSize: 9.5, fontWeight: 600, textAlign: "right", padding: "6px 4px", borderBottom: "1px solid #1c2230", position: "sticky", top: 0 },
  mTd: { padding: "5px 4px", textAlign: "right", borderBottom: "1px solid #151a26", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap" },
  mModel: { padding: "5px 4px", textAlign: "left", borderBottom: "1px solid #151a26", color: "#cfd6e4", whiteSpace: "normal", wordBreak: "break-word", lineHeight: 1.25 },
  mCat: { background: "#0e1218", color: "#8b94a7", fontSize: 9.5, fontWeight: 700, letterSpacing: 1, padding: "4px 6px", textTransform: "uppercase" },
  mLista: { width: "100%", boxSizing: "border-box", background: "#0b0e14", border: "1px solid #232a3a", color: "#c4b5fd", textAlign: "right", fontFamily: "inherit", fontSize: 11.5, padding: "3px 4px", borderRadius: 3, outline: "none" },
  tableBar: { display: "flex", alignItems: "center", gap: 14, flexWrap: "wrap", marginBottom: 10 },
  hideToggle: { display: "inline-flex", alignItems: "center", gap: 6, fontSize: 11.5, color: "#9aa3b5", cursor: "pointer" },
  hideCount: { color: "#525a6b", fontSize: 11 },
  markGroup: { display: "inline-flex", alignItems: "center", gap: 5, flexWrap: "wrap" },
  miniBtn: { background: "#1f2937", border: "1px solid #2a3346", color: "#cfd6e4", padding: "3px 9px", borderRadius: 4, cursor: "pointer", fontFamily: "inherit", fontSize: 11 },
  invTable: { borderCollapse: "collapse", width: "100%", marginTop: 8, border: "1px solid #1c2230" },
  invTh: { background: "#11151f", color: "#8b94a7", fontSize: 10, fontWeight: 600, textAlign: "right", padding: "6px 8px", borderBottom: "1px solid #1c2230" },
  invTd: { padding: "3px 8px", textAlign: "right", borderBottom: "1px solid #151a26", fontVariantNumeric: "tabular-nums" },
  invFoot: { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 10, flexWrap: "wrap", gap: 10, fontSize: 12, color: "#cfd6e4" },
  editBanner: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 6, background: "#1a2410", border: "1px solid #3a5a1d", color: "#cfe6b8", borderRadius: 6, padding: "8px 12px", marginBottom: 10, fontSize: 12 },
  acctTabs: { display: "flex", gap: 6, flexWrap: "wrap", padding: 8, background: "#0f131c", border: "1px solid #1c2230", borderRadius: 6 },
  acctTab: { display: "inline-flex", gap: 6, alignItems: "center", background: "#171c28", border: "1px solid #232a3a", color: "#aeb6c5", borderRadius: 5, padding: "5px 10px", cursor: "pointer", fontFamily: "inherit", fontSize: 12 },
  acctTabOn: { background: "#1d2740", borderColor: "#3a5b8f", color: "#e8ecf3" },
  acctMonth: { background: "#1a2233", color: "#8fb0dd", fontWeight: 700, fontSize: 11, letterSpacing: 1, padding: "4px 10px", textTransform: "uppercase" },
  pdfBtn: { background: "#16a34a", color: "#fff", padding: "8px 18px", borderRadius: 4, fontSize: 12.5, fontWeight: 600, textDecoration: "none", fontFamily: "inherit" },
  cotInputRow: { display: "flex", gap: 8, alignItems: "center", marginBottom: 10 },
  cotSearch: { flex: 1, maxWidth: 360, background: "#11151f", border: "1px solid #232a3a", color: "#e8ecf3", padding: "8px 10px", borderRadius: 4, fontFamily: "inherit", fontSize: 13, outline: "none" },
  chips: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 12 },
  chip: { display: "inline-flex", alignItems: "center", gap: 6, background: "#11151f", border: "1px solid #232a3a", borderRadius: 14, padding: "3px 6px 3px 10px", fontSize: 11.5, color: "#cfd6e4" },
  chipQty: { width: 38, background: "#0b0e14", border: "1px solid #232a3a", color: "#cfd6e4", borderRadius: 3, textAlign: "right", fontFamily: "inherit", fontSize: 11, padding: "1px 4px", outline: "none" },
  chipX: { cursor: "pointer", color: "#8b94a7", fontSize: 14, lineHeight: 1, padding: "0 2px" },
  chipSplit: { cursor: "pointer", color: "#6ea8fe", fontSize: 14, fontWeight: 700, lineHeight: 1, padding: "0 4px", marginLeft: 2 },
  planBar: { display: "flex", alignItems: "center", gap: 12, marginBottom: 10, flexWrap: "wrap" },
  planTabs: { display: "flex", gap: 6 },
  planTab: { background: "#11151f", border: "1px solid #232a3a", color: "#9aa3b5", padding: "6px 12px", borderRadius: 4, cursor: "pointer", fontFamily: "inherit", fontSize: 11.5 },
  planTabOn: { background: "#1e293b", borderColor: "#3b82f6", color: "#e8ecf3", fontWeight: 600 },
  planDelta: { fontSize: 10.5, color: "#6b7385" },
  planCards: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))", gap: 10 },
  planCard: { background: "#11151f", border: "1px solid #1c2230", borderRadius: 6, padding: 10 },
  planCardHead: { display: "flex", justifyContent: "space-between", alignItems: "baseline", borderBottom: "1px solid #1c2230", paddingBottom: 6, marginBottom: 6 },
  planSupplier: { fontSize: 13, fontWeight: 700, color: "#e8ecf3" },
  planSub: { fontSize: 10.5, color: "#6b7385" },
  planItem: { display: "flex", justifyContent: "space-between", gap: 8, padding: "2px 0", fontSize: 11.5 },
  planItemSku: { color: "#cfd6e4" },
  planQ: { color: "#6b7385" },
  planItemPrice: { color: "#cfd6e4", fontVariantNumeric: "tabular-nums" },
  staleTag: { color: "#fbbf24" },
  planFoot: { display: "flex", gap: 16, flexWrap: "wrap", alignItems: "center", marginTop: 10, fontSize: 11.5, color: "#cfd6e4" },
  uncoverable: { color: "#f87171" },
  planNote: { fontSize: 10, color: "#525a6b" },
  modeTabs: { display: "flex", gap: 6, marginBottom: 8 },
  askRow: { display: "flex", gap: 8, alignItems: "stretch" },
  imgBtn: { display: "inline-flex", alignItems: "center", background: "#1f2937", border: "1px solid #2a3346", color: "#cfd6e4", padding: "0 14px", borderRadius: 4, cursor: "pointer", fontFamily: "inherit", fontSize: 12, whiteSpace: "nowrap" },
  askInput: { flex: 1, background: "#11151f", border: "1px solid #232a3a", color: "#e8ecf3", padding: "9px 11px", borderRadius: 4, fontFamily: "inherit", fontSize: 13, outline: "none" },
  askBtn: { background: "#7c3aed", border: "none", color: "#fff", padding: "0 22px", borderRadius: 4, cursor: "pointer", fontFamily: "inherit", fontSize: 13, fontWeight: 600 },
  askHint: { fontSize: 10.5, color: "#525a6b", marginTop: 8 },
  answerCard: { background: "#11151f", border: "1px solid #1c2230", borderRadius: 6, padding: 12, marginTop: 10, fontSize: 13, color: "#dfe4ee", lineHeight: 1.6, whiteSpace: "pre-wrap" },
};

export default styles;
